site_name: MkDocs Boundless Bootstrap Theme
site_description: MkDocs Boundless  Bootstrap Theme
site_author: Boundless Spatial
repo_url: https://github.com/boundlessgeo/mkdocs-boundless
copyright: Copyright &copy; Boundless Spatial.
theme_dir: mkdocs_boundless
